"""Palavras-chave e leis citadas que indicam a matéria de uma questão.

Cada matéria tem uma lista de (peso, expressão regular). A pontuação só precisa separar
matérias vizinhas: quem decide a matéria final é a segmentação em blocos (classificar.py).
"""
import re

PADROES = {
"etica":[(5,r"Estatuto da Advocacia|EAOAB|Código de Ética e Disciplina|Regulamento Geral|Conselho Seccional|Tribunal de Ética|Conselho Federal da OAB|inscrição na OAB|inscrito na OAB|inscrita na OAB|sociedade de advogados|honorários advocatícios|desagravo|Caixa de Assistência|Subseç"),(2,r"\badvogad[oa]s?\b|\bOAB\b|estagiári|procuração|sigilo profissional|mandato|honorários")],
"filosofia":[(6,r"Kelsen|Hart\b|Bobbio|Aristóteles|Platão|Kant|Hegel|Rousseau|Hobbes|Locke|Dworkin|Rawls|Habermas|Montesquieu|Tomás de Aquino|Santo Agostinho|Marx|Weber|Radbruch|Alexy|Ihering|Savigny|Miguel Reale|Bentham|Stuart Mill|Nietzsche|Maquiavel|Cícero|Ulpiano|Luhmann|Foucault|Arendt|Perelman|Viehweg|Ross\b|Austin|Engisch|Posner|Sandel|Nozick|Grócio|Pufendorf|Durkheim|Bourdieu|Sócrates|Heidegger|Beccaria|Ferrajoli|Schmitt|Fuller|Recaséns|filósof|jusnatural|positivismo|teoria pura|justiça distributiva|equidade.{0,30}Aristóteles"),(3,r"\bobra\b|\blivro\b|segundo o autor|pensamento de|citação acima|trecho")],
"constitucional":[(4,r"Constituição(?! Estadual)|CRFB|\bCF/88\b|emenda constitucional|ADI\b|ADC\b|ADPF|ação direta de inconstitucionalidade|controle de constitucionalidade|mandado de injunção|habeas data|Supremo Tribunal Federal|Presidente da República|Congresso Nacional|Senado Federal|Câmara dos Deputados|Assembleia Legislativa|medida provisória|processo legislativo|CPI|comissão parlamentar|nacionalidade|brasileiro nato|naturaliza|direitos políticos|intervenção federal|Governador|Prefeito|repartição de competências|competência (legislativa|privativa|concorrente) da União|reclamação constitucional|súmula vinculante|plebiscito|referendo|iniciativa popular")],
"dh":[(6,r"direitos humanos|relator(a)? especial|escravidão|trabalho análogo|travesti|transexual|identidade de gênero|orientação sexual|LGBT|homofobia|racismo|Conselho Nacional de Direitos Humanos|Corte Interamericana|Comissão Interamericana|Convenção Americana|Pacto de San José|Pacto Internacional (sobre|de) Direitos|Declaração Universal|Sistema Interamericano|Sistema Global|ONU.{0,40}direitos|Conselho de Direitos Humanos|Estatuto da Pessoa com Deficiência|pessoa com deficiência|Convenção sobre os Direitos das Pessoas com Deficiência|tortura|refugiad|Estatuto da Igualdade Racial|discriminação racial|quilombol|indígena|povos originários|Convenção de Belém do Pará|Lei Maria da Penha|violência doméstica|trabalho escravo|incidente de deslocamento de competência|Protocolo de San Salvador|Estatuto do Idoso|Estatuto da Pessoa Idosa|população em situação de rua|Programa Nacional de Direitos Humanos")],
"internacional":[(6,r"Direito Internacional|tratado internacional|Convenção de Viena|Convenção de Haia|carta rogatória|homologação de sentença estrangeira|sentença estrangeira|extradição|\bLINDB\b|Lei de Introdução às Normas|Estatuto do Estrangeiro|Lei de Migração|migrante|asilo|apátrida|Mercosul|Organização Mundial do Comércio|\bOMC\b|Corte Internacional de Justiça|Tribunal Penal Internacional|imunidade de jurisdição|Estado estrangeiro|embaixad|cônsul|diplomát|Nações Unidas|domicílio no exterior|no exterior|estrangeir|sequestro internacional de crianças|arbitragem internacional|Protocolo de Las Leñas|regras de conexão|elemento de conexão")],
"tributario":[(5,r"tribut|imposto|\bICMS\b|\bIPI\b|\bISS\b|\bIPTU\b|\bIPVA\b|\bITBI\b|\bITCMD\b|\bIOF\b|\bIRPF?\b|imposto de renda|\bCTN\b|Código Tributário|contribuinte|contribuição de melhoria|taxa\b|lançamento|crédito tributário|fato gerador|execução fiscal|dívida ativa|isenção|imunidade tribut|anterioridade|responsabilidade tribut|contribuição social|Simples Nacional|substituição tributária|compensação tributária|repetição de indébito|Fazenda Pública.{0,40}(tribut|fiscal)|fisco")],
"administrativo":[(5,r"licitaç|Lei nº 14\.133|Lei nº 8\.666|contrato administrativo|servidor(a)? públic|servidores públicos|Lei nº 8\.112|improbidade|ato administrativo|poder de polícia|autarquia|empresa pública|sociedade de economia mista|fundação pública|agência reguladora|concessão de serviço|permissão de serviço|serviço público|desapropria|tombamento|servidão administrativa|requisição administrativa|bens públicos|responsabilidade civil do Estado|processo administrativo|Lei nº 9\.784|parceria público|consórcio público|concurso público|cargo público|Administração Pública|agente público|pregão|dispensa de licitação|inexigibilidade|Lei Anticorrupção|Lei nº 12\.846|terceiro setor|organizaç(ão|ões) social|OSCIP|estatuto da cidade|improbidade")],
"ambiental":[(6,r"ambient|Lei nº 9\.605|Lei nº 6\.938|Código Florestal|licenciamento|EIA|RIMA|unidade de conservação|área de preservação permanente|\bAPP\b|reserva legal|IBAMA|SNUC|poluiç|resíduos sólidos|recursos hídricos|fauna|flora|desmatamento|mineração|Política Nacional do Meio Ambiente|dano ecológico|patrimônio genético|biodiversidade|agrotóxic")],
"civil":[(4,r"Código Civil|usucapião|posse\b|possuidor|propriedade|condomínio|contrato de (compra e venda|locação|doação|mútuo|comodato|fiança|empreitada|seguro|mandato)|locação|locatári|locador|doação|herança|herdeir|sucessão|testamento|inventário|legítima|casamento|união estável|regime de bens|divórcio|alimentos|poder familiar|guarda|filiação|adoção|obrigaç|credor|devedor|responsabilidade civil|dano moral|indenização|prescrição|decadência|negócio jurídico|nulidade|anulabilidade|pessoa jurídica|personalidade|capacidade civil|incapaz|curatela|tutela\b|servidão|usufruto|hipoteca|penhor|alienação fiduciária|direito real|superfície|enfiteuse|evicção|vícios redibitórios|cláusula penal|juros|pagamento|dação|novação|compensação|remissão|solidariedade|fiador|vizinhança|registro de imóveis")],
"eca":[(7,r"Estatuto da Criança|\bECA\b|criança|adolescente|ato infracional|medida socioeducativa|Conselho Tutelar|internação provisória|remissão.{0,30}(adolescente|Ministério)|Vara da Infância|guarda.{0,30}(criança|menor)|adoção internacional|acolhimento institucional|família substituta|SINASE|menor de idade|infância e juventude")],
"consumidor":[(7,r"consumidor|Código de Defesa do Consumidor|\bCDC\b|fornecedor|relação de consumo|recall|publicidade enganosa|publicidade abusiva|prática abusiva|cláusula abusiva|vício do produto|fato do produto|vício do serviço|fato do serviço|superendividamento|PROCON|cadastro de inadimplentes|banco de dados.{0,30}consumidor|arrependimento|compra.{0,40}internet")],
"empresarial":[(5,r"sociedade (empresária|limitada|anônima|simples|em comandita|em nome coletivo|cooperativa)|empresári|\bEIRELI\b|Junta Comercial|registro (público )?de empresas|nome empresarial|estabelecimento empresarial|trespasse|falência|falid|recuperação (judicial|extrajudicial)|Lei nº 11\.101|administrador judicial|título(s)? de crédito|cheque|nota promissória|letra de câmbio|duplicata|endosso|aval\b|protesto|debênture|acionista|assembleia geral|conselho de administração|quotas?|cotas?|sócio|contrato social|propriedade industrial|marca|patente|desenho industrial|INPI|Lei nº 9\.279|franquia|representação comercial|contrato de (agência|distribuição|comissão|leasing|arrendamento mercantil|faturização|factoring)|microempresa|empresa de pequeno porte|startup|Lei das S\.A\.|Lei nº 6\.404|capital social|desconsideração da personalidade")],
"proc_civil":[(4,r"Código de Processo Civil|\bCPC\b|petição inicial|contestação|reconvenção|revelia|sentença|apelação|agravo de instrumento|agravo interno|embargos de declaração|embargos à execução|embargos de terceiro|recurso especial|recurso extraordinário|ação rescisória|cumprimento de sentença|execução de título|título executivo|penhora|tutela (provisória|de urgência|da evidência|antecipada|cautelar)|liminar|litisconsórcio|intervenção de terceiros|denunciação da lide|chamamento ao processo|assistência|amicus curiae|competência (absoluta|relativa)|foro|juízo|citação|intimação|prazo processual|preclusão|coisa julgada|honorários sucumbenciais|gratuidade de justiça|Juizados Especiais Cíveis|Lei nº 9\.099|mandado de segurança|ação monitória|ação de usucapião|inventário judicial|audiência de conciliação|audiência de instrução|réu|autor da ação|ajuizou|ajuizar|propôs ação|demanda|processo|incidente de resolução de demandas repetitivas|IRDR|precedente|negócio jurídico processual|ação popular|ação civil pública")],
"penal":[(4,r"Código Penal|\bCP\b|crime|delito|pena\b|penas|dolo|doloso|culpa|culposo|tentativa|consumação|legítima defesa|estado de necessidade|excludente de ilicitude|imputabilidade|inimputável|concurso de (agentes|pessoas|crimes)|crime continuado|reincid|prescrição da pretensão|extinção da punibilidade|furto|roubo|homicídio|lesão corporal|estelionato|receptação|latrocínio|extorsão|peculato|corrupção (passiva|ativa)|concussão|prevaricação|falsidade|estupro|tráfico de drogas|Lei nº 11\.343|Lei de Drogas|porte de arma|Estatuto do Desarmamento|crime hediondo|regime (inicial|fechado|semiaberto|aberto)|livramento condicional|sursis|suspensão condicional da pena|dosimetria|agravante|atenuante|causa de aumento|causa de diminuição|arrependimento posterior|desistência voluntária|erro de tipo|erro de proibição|medida de segurança|Lei de Execução Penal|LEP|progressão de regime|remição|crime de trânsito|Código de Trânsito|abuso de autoridade|lavagem de dinheiro|organização criminosa")],
"proc_penal":[(5,r"Código de Processo Penal|\bCPP\b|inquérito policial|denúncia|queixa-crime|ação penal|Ministério Público ofereceu|ofereceu denúncia|prisão (preventiva|temporária|em flagrante)|flagrante|audiência de custódia|liberdade provisória|fiança|habeas corpus|Tribunal do Júri|\bJúri\b|pronúncia|impronúncia|absolvição sumária|revisão criminal|recurso em sentido estrito|apelação criminal|embargos infringentes|juiz das garantias|acordo de não persecução|transação penal|suspensão condicional do processo|Juizado Especial Criminal|citação por edital.{0,30}réu|interrogatório|prova ilícita|busca e apreensão|interceptação telefônica|colaboração premiada|delegado|autoridade policial|Defensoria|defesa técnica|réu preso|nulidade (absoluta|relativa)|competência.{0,40}(Justiça Federal|Justiça Estadual).{0,40}crime|queixa|representação do ofendido|assistente de acusação|juiz criminal|vara criminal|execução penal|agravo em execução")],
"previdenciario":[(7,r"previdenci|INSS|segurad[oa]|aposentadoria|auxílio-(doença|acidente|reclusão)|auxílio por incapacidade|benefício de prestação continuada|\bBPC\b|LOAS|pensão por morte|salário-maternidade|salário-família|Lei nº 8\.213|Lei nº 8\.212|Regime Geral de Previdência|RGPS|carência|tempo de contribuição|contribuinte individual|segurado especial|seguridade social|assistência social")],
"financeiro":[(7,r"Direito Financeiro|orçament|Lei de Responsabilidade Fiscal|\bLRF\b|Lei Complementar nº 101|Lei nº 4\.320|lei de diretrizes orçamentárias|\bLDO\b|\bLOA\b|plano plurianual|\bPPA\b|crédito(s)? (adicional|suplementar|especial|extraordinário)|despesa pública|receita pública|receita corrente líquida|precatório|empenho|restos a pagar|operação de crédito|dívida pública|Tribunal de Contas|fundo de participação|transferências voluntárias|renúncia de receita")],
"eleitoral":[(8,r"eleitor|Justiça Eleitoral|Código Eleitoral|Lei nº 9\.504|Lei das Eleições|Lei nº 9\.096|partido político|partidos políticos|candidatura|registro de candidat|candidato a (Prefeito|Vereador|Deputado|Senador|Governador|Presidente)|propaganda eleitoral|campanha eleitoral|inelegib|Lei da Ficha Limpa|Lei Complementar nº 64|diplomação|registro de candidatura|TSE|Tribunal Superior Eleitoral|TRE|abuso de poder (econômico|político)|captação ilícita de sufrágio|AIJE|coligação|federação partidária|pleito eleitoral|mandato eletivo|fidelidade partidária|urna")],
"trabalho":[(4,r"\bCLT\b|Consolidação das Leis do Trabalho|empregad[oa]|empregador|contrato de trabalho|relação de emprego|vínculo empregatício|salário|remuneração|férias|13º|décimo terceiro|jornada|horas extras|hora extra|intervalo|adicional (de insalubridade|de periculosidade|noturno)|aviso prévio|FGTS|justa causa|rescisão|dispensa|estabilidade|gestante|terceirização|trabalho temporário|trabalho intermitente|teletrabalho|doméstic[oa]|sindicato|convenção coletiva|acordo coletivo|greve|equiparação salarial|comissões|gorjeta|trabalhador|cargo de confiança|reforma trabalhista|Lei nº 13\.467|dano extrapatrimonial|banco de horas")],
"proc_trabalho":[(6,r"reclamação trabalhista|Vara do Trabalho|Justiça do Trabalho|reclamante|reclamad[ao]|recurso ordinário|recurso de revista|agravo de petição|embargos à execução.{0,40}trabalh|depósito recursal|custas.{0,40}trabalh|TRT|TST|preposto|audiência trabalhista|rito sumaríssimo|procedimento sumaríssimo|inquérito para apuração de falta grave|dissídio coletivo|ação de cumprimento|execução trabalhista|homologação de acordo extrajudicial|juiz do trabalho|Ministério Público do Trabalho|jus postulandi|honorários de sucumbência.{0,40}trabalh")],
}
MATERIAS = list(PADROES)
_COMPILADOS = {m: [(w, re.compile(p, re.I)) for w, p in PADROES[m]] for m in MATERIAS}


def pontuar(texto):
    """{matéria: pontuação} — cada padrão conta até 3 ocorrências, com retorno decrescente."""
    out = {}
    for m in MATERIAS:
        v = 0
        for w, r in _COMPILADOS[m]:
            n = len(r.findall(texto))
            v += w * min(n, 3) ** 0.7 if n else 0
        out[m] = v
    return out
